Second day project.
MarcoAurelioAntonio/Vet-Clinic-rep pull request #2
Opened 2022-12-08 21:40 UTC by MarcoAurelioAntonio

Add a column species of type string to your animals table. Modify your schema.sql file.
Insert the following data:
Animal: His name is Charmander. He was born on Feb 8th, 2020, and currently weighs -11kg. He is not neutered and he has never tried to escape.
Animal: Her name is Plantmon. She was born on Nov 15th, 2021, and currently weighs -5.7kg. She is neutered and she has tried to escape 2 times.
Animal: His name is Squirtle. He was born on Apr 2nd, 1993, and currently weighs -12.13kg. He was not neutered and he has tried to escape 3 times.
Animal: His name is Angemon. He was born on Jun 12th, 2005, and currently weighs -45kg. He is neutered and he has tried to escape once.
Animal: His name is Boarmon. He was born on Jun 7th, 2005, and currently weighs 20.4kg. He is neutered and he has tried to escape 7 times.
Animal: Her name is Blossom. She was born on Oct 13th, 1998, and currently weighs 17kg. She is neutered and she has tried to escape 3 times.
Animal: His name is Ditto. He was born on May 14th, 2022, and currently weighs 22kg. He is neutered and he has tried to escape 4 times.
Remember to add these insertions to your data.sql file.
Inside a transaction update the animals table by setting the species column to unspecified. Verify that change was made. Then roll back the change and verify that the species columns went back to the state before the transaction.
Inside a transaction:
Update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
Update the animals table by setting the species column to pokemon for all animals that don't have species already set.
Commit the transaction.
Verify that change was made and persists after commit.
Take a screenshot of the results of your actions.
Now, take a deep breath and... Inside a transaction delete all records in the animals table, then roll back the transaction.
After the rollback verify if all records in the animals table still exists. After that, you can start breathing as usual ;)
Take a screenshot of the results of your actions.
Inside a transaction:
Delete all animals born after Jan 1st, 2022.
Create a savepoint for the transaction.
Update all animals' weight to be their weight multiplied by -1.
Rollback to the savepoint
Update all animals' weights that are negative to be their weight multiplied by -1.
Commit transaction
Take a screenshot of the results of your actions.
Remember to add all these transactions to your queries.sql file.
Write queries to answer the following questions:
How many animals are there?
How many animals have never tried to escape?
What is the average weight of animals?
Who escapes the most, neutered or not neutered animals?
What is the minimum and maximum weight of each type of animal?
What is the average number of escape attempts per animal type of those born between 1990 and 2000?
Take a screenshot of the results of your queries.
Remember to add these queries to your queries.sql file.
Remember to add screenshots with the results of your queries and with the results of your play with transactions to your Pull Request description.

![image](https://user-images.githubusercontent.com/99001924/199623979-54b2995c-baf1-4916-90c2-9679a751ca6d.png)

![image](https://user-images.githubusercontent.com/99001924/199741153-a2016fb5-c57d-4d84-a10d-a7bfcf9c3ada.png)

![image](https://user-images.githubusercontent.com/99001924/199774818-8a832497-0d38-4bb7-9d37-db2ef8b440c4.png)

![image](https://user-images.githubusercontent.com/99001924/199775661-a604b22f-607c-42a2-87fe-115821cda65d.png)

![image](https://user-images.githubusercontent.com/99001924/199777436-3d3c3871-57ad-47cc-815a-8f7846709828.png)
![image](https://user-images.githubusercontent.com/99001924/199777521-0f92d531-0c71-4493-833d-538df7020407.png)

![image](https://user-images.githubusercontent.com/99001924/199780897-3e1b8b7d-32b8-4a6e-9000-61647b4410da.png)
![image](https://user-images.githubusercontent.com/99001924/199781039-acdbacf4-5923-490d-9f5f-e263c36cb036.png)

2022-12-08 21:54 UTC, codecaiine requested changes
Hi @MarcoAurelioAntonio , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses the old readme version :cry: There is a new  [README available](https://github.com/microverseinc/readme-template/edit/master/README.md) template. Please make sure to update your README file using the new README template version. :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-08 23:18 UTC, Gambit142 requested changes
Hi @MarcoAurelioAntonio 👋, 

Good job so far!

### Highlights
- All codes for creating, structuring and altering tables are in the _**schema.sql**_ file ✔️ 
- All codes that populate tables with data are in the _**data.sql**_ file ✔️ 
- All codes that query or help to analyze data are in the _**queries.sql**_ file ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-08 23:18 UTC, Gambit142 commented on schema.sql
>  );
- [ ] Instead of adding the species column manually, I would suggest you alter the table and add the name of the desired column and column type. 👍 

For example:
```SQL
ALTER TABLE table_name
  ADD column_name column_type;
```

Please do not set this column to not nullable because of the transactions you wrote in the queries.sql.

```SQL
BEGIN;
UPDATE animals SET species = 'digimon'
WHERE name LIKE '%mon';
UPDATE animals SET species = 'pokemon'
WHERE species IS NULL;
```

2022-12-08 23:18 UTC, Gambit142 commented on data.sql
> +('Ditto', DATE '2022 05 14', 22, true, 4);
- [ ] You inserted the wrong data into this table. Kindly input the correct data. You can find details of the correct data [here](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md). Kindly focus on the data entered for the `weight_kg` column. 💻

2022-12-08 23:18 UTC, Gambit142 commented on queries.sql
> +SELECT COUNT(*) AS "Escapee_Animals_Count" FROM animals WHERE escape_attempts = 0;
- [ ] The result returned for this query is `2` and not `1`. `Charmander` and `Agumon` never tried to escape. The statement is correct but the data inputted has errors. Kindly input the correct data and update your screenshot. 👍

2022-12-09 15:18 UTC, Davidosky007 approved these changes
Hi @MarcoAurelioAntonio 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 19:23 UTC, merged